Merge Routine
HISMalawi/BHT-EMR-API pull request #104
Opened 2022-01-25 17:55 UTC by Skipper-116

new way of merging patients so that we are able to revert them after.

2022-01-26 07:05 UTC, fchiyenda requested changes
Hello Don't you think we should use encounter_datetime for the check instead of date_created

2022-02-01 13:11 UTC, Skipper-116 commented
@fchiyenda now i have incorporated encounter_datetime as well as obs_datetime on observation

2022-02-09 08:03 UTC, mwatha approved these changes

2022-06-13 12:11 UTC, sulemartin87 approved these changes

2022-06-13 14:03 UTC, sulemartin87 approved these changes

2022-06-13 14:03 UTC, merged