New HTS Encounter Types
HISMalawi/BHT-EMR-API pull request #207
Opened 2022-08-29 07:12 UTC by Skipper-116

These are the new encounter types

```bash
194	Partner Reception
195	HTS Contact
```
These are the accompanying concepts
```bash
10588      Positive Art unknown
10589	Sexual Partner
10590	Biological Children
10591	Biological Parents
10592	Self-Test Kit
10593	Contact physical address
10594	IPV Status
10595	Risk
10596	No Risk
10597	Consent to contact the contact
10598	Notification Means
10599	Provider referral
10600	Contact referral
10601	Self-Test and FRS
```
This fixes issue #196 and #195

2022-08-30 09:54 UTC, andie23 requested changes
Daul referral concept is missing

2022-08-31 06:42 UTC, Skipper-116 commented
Added the dual referral concept @andie23 
```bash
10602 Dual referral
```

2022-08-31 07:52 UTC, andie23 approved these changes

2022-08-31 07:52 UTC, andie23 commented
The HTS branch will now be our base branch for future updates until the module is ready

2022-08-31 07:52 UTC, merged