Opd hmi15 report fix
HISMalawi/BHT-EMR-API pull request #214
Opened 2022-09-15 07:59 UTC by dominickasanga

- a fix hmi15 conditions, which was not capturing all
- added and endpont for caputing opd attendance, based on encounters done in opd

2022-09-16 06:25 UTC, Skipper-116 requested changes

2022-09-16 06:25 UTC, Skipper-116 commented on app/controllers/api/v1/reports_controller.rb
> +    puts( params.require %i[start_date end_date])
This is not necessary in production... Can we utilize the ProgramReportsController#Show (action method)

2022-09-16 06:25 UTC, Skipper-116 commented on app/services/opd_service/report_engine.rb
> +    def attendance(start_date, end_date)
Add this under REPORTS in OPDService::ReportEngine then add a class or module that handles this

2022-09-16 06:25 UTC, Skipper-116 commented on app/services/report_service.rb
> +    engine(@program).attendance(start_date, end_date)
This will not be necessary after you add those on recommendation on top

2022-09-16 06:25 UTC, Skipper-116 commented on config/routes.rb
> +  get '/api/v1/attendance' => 'api/v1/reports#attendance'
This will not be required after you add those on top

2022-09-18 11:31 UTC, Skipper-116 approved these changes

2022-09-18 11:31 UTC, Skipper-116 commented on .~lock.migration_scores_20220915.csv#
> +,dominic,Dom-Stig,15.09.2022 18:24,file:///home/dominic/.config/libreoffice/4;
This file is part of the report?

2022-09-18 15:35 UTC, dominickasanga commented on .~lock.migration_scores_20220915.csv#
> +,dominic,Dom-Stig,15.09.2022 18:24,file:///home/dominic/.config/libreoffice/4;
no.. let me remove it

2022-09-18 15:38 UTC, dominickasanga commented on .~lock.migration_scores_20220915.csv#
> +,dominic,Dom-Stig,15.09.2022 18:24,file:///home/dominic/.config/libreoffice/4;
no.. its not

2022-09-19 08:11 UTC, merged