OPD fixing STIs and additional of drug and diagnosis
HISMalawi/BHT-EMR-API pull request #285
Opened 2023-01-10 07:44 UTC by petroskayange

1. fixing OPD STIs
2. Adding OPD diagnosis = Genital herpes,haemorrhoids
3. Adding OPD drug = cenfixine 400mg

2023-01-11 09:07 UTC, Skipper-116 commented on db/idsr_metadata/idsr_ohsp_settings.json.example
> +	"sms_server":   {"url":"10.40.30.11:8186/submit","user":"admin@email.test","pass":"administrator"},
Are these actual credentials? Is this possible to be moved to the configurations

2023-01-11 09:11 UTC, Skipper-116 reviewed
From what i'm seeing we need to stop tracking the idsr_ohsp_settings.json othewise we are tracking credentials on a public repo.

2023-01-11 09:12 UTC, Skipper-116 requested changes
Just changes on the idsr_metadata

2023-01-11 13:51 UTC, petroskayange commented on db/idsr_metadata/idsr_ohsp_settings.json.example
> +	"sms_server":   {"url":"10.40.30.11:8186/submit","user":"admin@email.test","pass":"administrator"},
Alright let me move them

2023-01-20 09:11 UTC, Skipper-116 approved these changes

2023-01-24 09:25 UTC, merged