Fixing OPD dashboard report
HISMalawi/BHT-EMR-API pull request #327
Opened 2023-04-13 07:52 UTC by petroskayange

Changes to be committed:
	modified:   app/services/opd_service/report_engine.rb

2023-04-13 14:18 UTC, uniquedj95 requested changes

2023-04-13 14:18 UTC, uniquedj95 commented on app/services/opd_service/report_engine.rb
> +        joins('INNER JOIN concept_name c ON c.concept_id = obs.value_coded').\
Use COALESCE to check if value_coded has a value and default to value_text for compatibility with the previous data set.

2023-04-13 14:19 UTC, uniquedj95 requested changes
Refer to the comments in the files for specific changes

2023-04-17 12:46 UTC, Skipper-116 approved these changes

2023-04-17 12:46 UTC, merged