create tx_tb report
HISMalawi/BHT-EMR-API pull request #378
Opened 2023-06-28 10:04 UTC by brian-mw

This shows TX_TB report

![image](https://github.com/HISMalawi/BHT-EMR-API/assets/42282752/8f3c105b-6d19-4e0d-b847-d6e35650ccff)

response

![image](https://github.com/HISMalawi/BHT-EMR-API/assets/42282752/b3a4df6c-6c2e-49e4-a5b1-07487514f79a)

2023-06-29 13:51 UTC, Skipper-116 requested changes

2023-06-29 13:51 UTC, Skipper-116 commented on app/services/art_service/report_engine.rb
> +    def tx_tb(start_date, end_date)
This is not necessary as long as the find_report method is defined on the TxTB class

2023-06-30 08:33 UTC, uniquedj95 commented
Gender field is missing

2023-07-03 07:09 UTC, andie23 approved these changes

2023-07-03 10:11 UTC, Skipper-116 approved these changes

2023-07-03 10:11 UTC, merged