voiding lab order in nlims when the order is voided in EMR
HISMalawi/BHT-EMR-API pull request #388
Opened 2023-07-20 12:38 UTC by petroskayange

2023-07-26 13:12 UTC, Skipper-116 requested changes

2023-07-26 13:12 UTC, Skipper-116 commented on app/controllers/api/v1/encounters_controller.rb
> +    encounter_service.destroy_lab_order_lims(encounter.encounter_id)
This is not necessary.

2023-07-26 13:12 UTC, Skipper-116 commented on app/services/encounter_service.rb
> +  def destroy_lab_order_lims(encounter_id)
Handle this in the encounter model under after void. It already voids all orders. You might want to segregate this code to only handle lab orders only

2023-07-28 14:23 UTC, petroskayange commented on app/services/encounter_service.rb
> +  def destroy_lab_order_lims(encounter_id)
It is done

2023-08-14 07:54 UTC, Skipper-116 approved these changes

2023-09-13 10:02 UTC, merged