Fix/opd drug report
HISMalawi/BHT-EMR-API pull request #458
Opened 2023-10-24 10:57 UTC by petroskayange

Developing a new query that gets drug details.

2023-10-26 14:37 UTC, uniquedj95 commented
You need to remove the parts related to the replaced reports (i.e. `drugs_given_without_prescription` and `drugs_given_with_prescription`). This will make the code clean and easy to maintain.

2023-10-26 14:49 UTC, uniquedj95 requested changes
The pr is returning internal server error with the following error

ActiveRecord::StatementInvalid (Mysql2::Error: Subquery returns more than 1 row: SELECT

2023-10-27 04:56 UTC, petroskayange commented
> The pr is returning internal server error with the following error
> 
> ActiveRecord::StatementInvalid (Mysql2::Error: Subquery returns more than 1 row: SELECT

fixed

2023-10-27 10:03 UTC, uniquedj95 approved these changes

2023-11-09 13:04 UTC, Skipper-116 commented on app/services/opd_service/reports/drug.rb
> +      ) as diagnosis,
This will definitely make the code slower. Best to have simple select in the select sections. I believe a restructured query will be ideal

2023-11-09 13:46 UTC, Skipper-116 requested changes
Can you restructure the query

2023-12-07 09:31 UTC, Skipper-116 approved these changes

2023-12-07 09:32 UTC, merged