Fixes crashing issue when retrieving tpt status
HISMalawi/BHT-EMR-API pull request #531
Opened 2024-03-25 14:06 UTC by andie23

## Context
Extra check has been added to prevent crashing when retrieving arv drug expire date.
Identified a client from MPC facility for whom the tpt_status endpoing would crash because date result hash is nil. This has been handled gracefully

## Reference
https://app.shortcut.com/egpaf-2/story/2779/backend-crashing-when-loading-tpt-status-on-consultation-page

2024-03-26 07:37 UTC, anthony-kakatera approved these changes

2024-03-26 13:48 UTC, Skipper-116 requested changes

2024-03-26 13:48 UTC, Skipper-116 commented on app/models/patient.rb
> +    result['auto_expire_date']&.to_date || nil if !result.blank?
For readability
```suggestion
result['auto_expire_date']&.to_date || nil if result.present?
```
OR

```suggestion
result['auto_expire_date']&.to_date || nil unless result.blank?
```

2024-03-27 09:58 UTC, anthony-kakatera approved these changes

2024-03-27 10:42 UTC, Skipper-116 approved these changes

2024-03-27 10:42 UTC, merged