Dashboard fix
HISMalawi/BHT-EMR-API pull request #617
Opened 2024-08-02 10:41 UTC by Senzenjani

2024-08-04 17:57 UTC, fchiyenda requested changes

2024-08-04 17:57 UTC, fchiyenda commented on app/services/immunization_service/follow_up.rb
> +          missed_antigens = visit[:antigens].select { |antigen| antigen[:can_administer] && antigen[:status] == "pending" && visit[:milestone_status] == "passed" }
Seems this is not working because vaccine administration seems not to be saving location_id hence fetch_immunization_clients to able to fetch clients

2024-08-04 17:57 UTC, fchiyenda commented on app/services/immunization_service/follow_up.rb
>              due_date = calculate_due_date(immunization_client.birthdate, visit[:age])
I am thinking if instead of shifting in calculate_due_date if we would add and seems you might have also missed the months in month calculation

2024-08-05 12:19 UTC, Senzenjani commented
I have moved the triggering of job to programs controller than patient controller because patient gets created then enrolled to immunization program. So at that moment that is when the patient becomes an immunization client. So running the jobs after enrolling the patient will make the patient available for followup calculation logic, hence the change.

2024-08-05 12:58 UTC, fchiyenda approved these changes

2024-08-05 12:59 UTC, merged