removed validation code
HISMalawi/BHT-EMR-API pull request #648
Opened 2024-08-25 11:19 UTC by pamzey

I have removed the validation code for phone number and also added condition for initiating a reminder job also checks if sms notification is active

2024-08-25 17:52 UTC, pamzey commented
I have added site specific configurations for sms

2024-08-26 10:57 UTC, fchiyenda requested changes

2024-08-26 10:57 UTC, fchiyenda commented on app/controllers/api/v1/send_sms_controller.rb
> +    GlobalProperty.where("property LIKE ?", "#{facility_id}_%")
Let us be specific here let us not use like

2024-08-26 10:57 UTC, fchiyenda commented on app/jobs/send_sms_job.rb
> +    sms_gateway_url = get_global_property("#{facility_id}_sms_gateway_url")
Let us not keep api_key and sms gateway in the database let still maintain it in the config file application.yml let us only keep the messages we send in the db.

2024-09-04 08:50 UTC, closed without merging